"""Initial schema

Revision ID: 62f461946a42
Revises:
Create Date: 2025-12-21 18:37:46.927725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f461946a42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citation_number', sa.String(length=50), nullable=False),
    sa.Column('violation_date', sa.String(length=20), nullable=True),
    sa.Column('vehicle_info', sa.String(length=200), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_address_line1', sa.String(length=200), nullable=False),
    sa.Column('user_address_line2', sa.String(length=200), nullable=True),
    sa.Column('user_city', sa.String(length=50), nullable=False),
    sa.Column('user_state', sa.String(length=2), nullable=False),
    sa.Column('user_zip', sa.String(length=10), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('user_phone', sa.String(length=20), nullable=True),
    sa.Column('appeal_reason', sa.Text(), nullable=True),
    sa.Column('selected_evidence', sa.JSON(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intakes_citation_number'), 'intakes', ['citation_number'], unique=False)
    op.create_index('ix_intakes_citation_status', 'intakes', ['citation_number', 'status'], unique=False)
    op.create_index('ix_intakes_created_at', 'intakes', ['created_at'], unique=False)
    op.create_index(op.f('ix_intakes_id'), 'intakes', ['id'], unique=False)
    op.create_index(op.f('ix_intakes_user_email'), 'intakes', ['user_email'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('appeal_type', sa.Enum('STANDARD', 'CERTIFIED', name='appealtype'), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('refined_text', sa.Text(), nullable=True),
    sa.Column('is_ai_refined', sa.Boolean(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.Column('ai_prompt_version', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drafts_created_at', 'drafts', ['created_at'], unique=False)
    op.create_index(op.f('ix_drafts_id'), 'drafts', ['id'], unique=False)
    op.create_index(op.f('ix_drafts_intake_id'), 'drafts', ['intake_id'], unique=False)
    op.create_index('ix_drafts_intake_type', 'drafts', ['intake_id', 'appeal_type'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=100), nullable=False),
    sa.Column('stripe_payment_intent', sa.String(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('amount_total', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('appeal_type', sa.Enum('STANDARD', 'CERTIFIED', name='appealtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('is_fulfilled', sa.Boolean(), nullable=True),
    sa.Column('fulfillment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lob_tracking_id', sa.String(length=100), nullable=True),
    sa.Column('lob_mail_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_fulfillment', 'payments', ['is_fulfilled', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_intake_id'), 'payments', ['intake_id'], unique=False)
    op.create_index('ix_payments_status_created', 'payments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_payments_stripe_customer_id'), 'payments', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent'), 'payments', ['stripe_payment_intent'], unique=False)
    op.create_index('ix_payments_stripe_session', 'payments', ['stripe_session_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_session_id'), 'payments', ['stripe_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_session_id'), table_name='payments')
    op.drop_index('ix_payments_stripe_session', table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_payment_intent'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_customer_id'), table_name='payments')
    op.drop_index('ix_payments_status_created', table_name='payments')
    op.drop_index(op.f('ix_payments_intake_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index('ix_payments_fulfillment', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_drafts_intake_type', table_name='drafts')
    op.drop_index(op.f('ix_drafts_intake_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_id'), table_name='drafts')
    op.drop_index('ix_drafts_created_at', table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_intakes_user_email'), table_name='intakes')
    op.drop_index(op.f('ix_intakes_id'), table_name='intakes')
    op.drop_index('ix_intakes_created_at', table_name='intakes')
    op.drop_index('ix_intakes_citation_status', table_name='intakes')
    op.drop_index(op.f('ix_intakes_citation_number'), table_name='intakes')
    op.drop_table('intakes')
    # ### end Alembic commands ###

