#!/bin/bash

# Manual SSL Setup Instructions
# Run these commands on your server: 178.156.215.100

DOMAIN="fightcitytickets.com"
SERVER_IP="178.156.215.100"

echo "=========================================="
echo "SSL Certificate Setup - Manual Steps"
echo "=========================================="
echo ""
echo "SSH into your server first:"
echo "  ssh root@$SERVER_IP"
echo ""
echo "Then run these commands:"
echo ""
echo "1. Install Certbot:"
echo "   apt-get update"
echo "   apt-get install -y certbot python3-certbot-nginx"
echo ""
echo "2. Get SSL certificate:"
echo "   certbot --nginx -d $DOMAIN -d www.$DOMAIN"
echo ""
echo "3. Follow the prompts:"
echo "   - Enter your email address"
echo "   - Agree to terms of service"
echo "   - Choose to redirect HTTP to HTTPS (recommended)"
echo ""
echo "4. Test auto-renewal:"
echo "   certbot renew --dry-run"
echo ""
echo "5. Verify certificate:"
echo "   certbot certificates"
echo ""
echo "=========================================="
echo "After SSL is set up:"
echo "=========================================="
echo ""
echo "1. Update your .env file:"
echo "   CORS_ORIGINS=https://$DOMAIN,https://www.$DOMAIN"
echo "   APP_URL=https://$DOMAIN"
echo "   API_URL=https://$DOMAIN"
echo ""
echo "2. Restart your services:"
echo "   docker-compose restart"
echo ""
echo "3. Test your site:"
echo "   https://$DOMAIN"
echo "   https://www.$DOMAIN"
echo ""
echo "=========================================="

